#! /bin/sh
#
# snatch       Start the Linux-SNA Transaction Programs Attach Manager.
#
# Author:       Jay Schulist <jschlst@samba.org>
#
# chkconfig: 345 50 50
#
# description: The sna attach daemon (commonly called snatchd) \
#              starts a variety of other sna services as needed. It \
#              is responsible for starting many services, including aping, \
#              aftp, aname, and arexec. Disabling snatchd disables all of the \
#              services it is responsible for.
#
# processname: snatchd
# pidfile: /var/run/snatchd.pid
# config: /etc/snatchd.conf


# Source function library.
. /etc/rc.d/init.d/functions

. /etc/sysconfig/network

# Check that SNA networking is up.
[ ${SNA} = "no" ] && exit 0

[ -f /usr/sbin/snatchd ] || exit 0

# See how we were called.
case "$1" in
  start)
	echo -n "Starting Linux-SNA Attach services: "
	daemon snatchd

	echo
	touch /var/lock/subsys/snatch
	;;
  stop)
	echo -n "Stopping Linux-SNA Attach services: "
	killproc snatchd

	echo
	rm -f /var/lock/subsys/snatch
	;;
  status)
	status snatchd
	;;
  restart|reload)
	killall -HUP snatchd
	;;
  *)
	echo "Usage: snatch {start|stop|status|restart|reload}"
	exit 1
esac

exit 0
